name: infra-as-code

# Manually triggered
on:
  workflow_dispatch:
    inputs:
        envname:
          description: 'Environment (one of "dev" or "prod")'
          required: true
          default: 'dev'

jobs:
  deploy:
    name: Upload Lambda code and model to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Deploying to ${{ github.event.inputs.name }}
      run: echo "EnvironmentName=${{ github.event.inputs.name }}"

    - name: pwd and ls
      run: |
        pwd
        ls -lrtR

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: S3Stack
        template: cloudformation/S3.yaml
        parameter-overrides: "EnvironmentName=${{ github.event.inputs.name }}"
